In [78]:
import pandas as pd
import numpy as np
import preprocessing as pre

In [55]:
real = [1.,163.,72.,0.,0.,39.,1.222,33.]

In [56]:
real = np.asarray(real).reshape(1,-1)

In [57]:
real

array([[  1.   , 163.   ,  72.   ,   0.   ,   0.   ,  39.   ,   1.222,
         33.   ]])

In [58]:
df = pd.DataFrame(real, columns = ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age'])

In [59]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          1.0    163.0           72.0            0.0      0.0  39.0   

   DiabetesPedigreeFunction   Age  
0                     1.222  33.0

In [79]:
pre.col_list

['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']

In [61]:
def ageRange(age):
    if 21 <= age < 30:
        return 1
    elif 30 <= age < 40:
        return 2
    elif 40 <= age < 50:
        return 3
    elif 50 <= age < 60:
        return 4
    elif 60 <= age < 70:
        return 5
    else:
        return 6

In [80]:
df['Age2'] = df['Age'].apply(pre.ageRange)

In [63]:
import pickle

In [64]:
with open('dict_total.pkl', 'rb') as f:
    dict_total = pickle.load(f)

In [65]:
df.loc[0, 'SkinThickness'] =dict_total['SkinThickness'][df.loc[0]['Age2']]

In [66]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          1.0    163.0           72.0           32.0      0.0  39.0   

   DiabetesPedigreeFunction   Age  Age2  
0                     1.222  33.0     2

In [67]:
for col in col_list:
    df.loc[0, col] = dict_total[col][df.loc[0]['Age2']]

In [68]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          1.0    122.0           74.0           32.0    140.0  32.0   

   DiabetesPedigreeFunction   Age  Age2  
0                     1.222  33.0     2

In [69]:
df.drop('Age2', axis = 1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          1.0    122.0           74.0           32.0    140.0  32.0   

   DiabetesPedigreeFunction   Age  
0                     1.222  33.0

In [70]:
with open('diabet_model.pkl', 'rb') as f:
    diabet_model = pickle.load(f)

In [71]:
predict = diabet_model.predict(real)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [75]:
predict

array([0], dtype=int64)

In [77]:
if predict == 0:
    '당뇨가 없습니다.'
else:
    '당뇨입니다.'

In [73]:
real

array([[  1.   , 122.   ,  74.   ,  32.   , 140.   ,  32.   ,   1.222,
         33.   ]])

In [ ]:
def prefunc(df):
    
    for col in col_list:
        data[col] = np.where(data[col] == 0, np.nan, data[col])
        
        


In [81]:
for col in col_list:
    print(dict_total[col])

{1: 109.0, 2: 122.0, 3: 123.0, 4: 139.0, 5: 136.0, 6: 134.0}
{1: 68.0, 2: 74.0, 3: 78.0, 4: 78.0, 5: 78.0, 6: 78.0}
{1: 27.0, 2: 32.0, 3: 31.0, 4: 28.5, 5: 31.0, 6: 25.5}
{1: 105.0, 2: 140.0, 3: 131.0, 4: 192.0, 5: 258.0, 6: 60.0}
{1: 31.6, 2: 32.0, 3: 33.95, 4: 33.05, 5: 29.3, 6: 25.9}


In [83]:
dict_total['BMI']

NameError: name 'data' is not defined

In [86]:
[df.loc[0]['Age2']]

[2.0]

In [92]:
dict_total['BMI'][df.loc[0]['Age2']] # age2 값에 따라, BMI의 value 도출

32.0