In [1]:
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LogisticRegressionCV
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import StandardScaler
import pickle
from sklearn.preprocessing import PolynomialFeatures

In [2]:
df=pd.read_csv('heart.csv')

In [3]:
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [5]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [6]:
df.value_counts()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  ca  thal  target
38   1    2   138       175   0    1        173      0      0.0      2      4   2     1         2
59   1    0   110       239   0    0        142      1      1.2      1      1   3     0         1
          2   126       218   1    1        134      0      2.2      1      1   1     0         1
          1   140       221   0    1        164      1      0.0      2      0   2     1         1
          0   170       326   0    0        140      1      3.4      0      0   3     0         1
                                                                                               ..
51   1    2   94        227   0    1        154      1      0.0      2      1   3     1         1
          0   140       299   0    1        173      1      1.6      2      0   3     0         1
                        298   0    1        122      1      4.2      1      3   3     0         1
                        2

In [7]:
x=df.drop('target',axis=1)
y=df['target']

In [8]:
pol= PolynomialFeatures(degree=4)
x_pol= pol.fit_transform(x)
x_pol

array([[ 1., 63.,  1., ...,  0.,  0.,  1.],
       [ 1., 37.,  1., ...,  0.,  0., 16.],
       [ 1., 41.,  0., ...,  0.,  0., 16.],
       ...,
       [ 1., 68.,  1., ..., 36., 54., 81.],
       [ 1., 57.,  1., ...,  9., 27., 81.],
       [ 1., 57.,  0., ...,  4.,  8., 16.]])

In [9]:
x_train, x_test, y_train, y_test=train_test_split(x_pol,y,test_size=0.2,random_state=2) #PolynomialFeatures를 사용하려면 pol_x를 x에 넣을 것!  대신 되게 오래 걸려 

In [10]:
model=LogisticRegressionCV(max_iter=1000,cv=3)
model.fit(x_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i 

LogisticRegressionCV(cv=3, max_iter=1000)

In [11]:
model

LogisticRegressionCV(cv=3, max_iter=1000)

In [12]:
len(x_train)

242

In [13]:
model.score(x_train,y_train)

0.8842975206611571

In [14]:
model.score(x_test,y_test)

0.8360655737704918

In [15]:
with open('scaler.pkl','rb')as f:#### 저장한거 불러오기
    scaler=pickle.load(f)

In [16]:
real = [35, 1, 2, 135, 240, 0, 0, 160, 1, 2.1, 1, 0, 1]

In [17]:
model2=LogisticRegression()

In [18]:
model2.fit(x_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [19]:
x.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal'],
      dtype='object')

In [20]:
model2.coef_ ###wx

array([[ 7.72435811e-17,  5.27488563e-15, -2.71912502e-15, ...,
         3.32094564e-14, -1.65308736e-14, -1.48489319e-13]])

In [21]:
model2.intercept_ ### b

array([7.72435811e-17])

In [22]:
real1=np.asarray(real).reshape(1,-1)### 리스트의 형식은 reshape을 할 수 없어서 np를 이용해서 asarray로 바꾼다

In [23]:
real1

array([[ 35. ,   1. ,   2. , 135. , 240. ,   0. ,   0. , 160. ,   1. ,
          2.1,   1. ,   0. ,   1. ]])

In [24]:
reall=pol.transform(real1)

C:\Users\user\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


In [25]:
reall

array([[ 1., 35.,  1., ...,  0.,  0.,  1.]])

In [26]:
model2.predict(reall)

array([1], dtype=int64)

In [27]:
df.target.value_counts()

1    165
0    138
Name: target, dtype: int64

### 남자가 여자보다 많다  
데이터 분석 한 내용을 노트에 적어라

In [28]:
df.sex.value_counts()

1    207
0     96
Name: sex, dtype: int64